dmoj/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.http import Http404, HttpResponsePermanentRedirect
from django.templatetags.static import static
from django.urls import path, reverse
from django.utils.functional import lazystr
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView
from martor.views import markdown_search_user

from judge.feed import AtomBlogFeed, AtomCommentFeed, AtomProblemFeed, BlogFeed, CommentFeed, ProblemFeed
from judge.sitemap import BlogPostSitemap, ContestSitemap, HomePageSitemap, OrganizationSitemap, ProblemSitemap, \
    SolutionSitemap, UrlSitemap, UserSitemap
from judge.views import TitledTemplateView, api, blog, comment, contests, language, license, mailgun, organization, \
    preview, problem, problem_manage, ranked_submission, register, stats, status, submission, tasks, ticket, \
    two_factor, user, widgets, about
from judge.views.problem_data import ProblemDataView, ProblemSubmissionDiff, \
    problem_data_file, problem_init_view
from judge.views.register import ActivationView, RegistrationView
from judge.views.select2 import AssigneeSelect2View, CommentSelect2View, ContestSelect2View, \
    ContestUserSearchSelect2View, OrganizationSelect2View, ProblemSelect2View, TicketUserSelect2View, \
    UserSearchSelect2View, UserSelect2View
from judge.views.widgets import martor_image_uploader

admin.autodiscover()

register_patterns = [
    url(r'^activate/complete/$',
        TitledTemplateView.as_view(template_name='registration/activation_complete.html',
                                   title='Activation Successful!'),
        name='registration_activation_complete'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    url(r'^activate/(?P<activation_key>\w+)/$',
        ActivationView.as_view(title='Activation key invalid'),
        name='registration_activate'),
    url(r'^register/$',
        RegistrationView.as_view(title='Register'),
        name='registration_register'),
    url(r'^register/complete/$',
        TitledTemplateView.as_view(template_name='registration/registration_complete.html',
                                   title='Registration Completed'),
        name='registration_complete'),
    url(r'^register/closed/$',
        TitledTemplateView.as_view(template_name='registration/registration_closed.html',
                                   title='Registration not allowed'),
        name='registration_disallowed'),
    url(r'^login/$', user.CustomLoginView.as_view(), name='auth_login'),
    url(r'^logout/$', user.UserLogoutView.as_view(), name='auth_logout'),
    url(r'^password/change/$', user.CustomPasswordChangeView.as_view(), name='password_change'),
    url(r'^password/change/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
    ), name='password_change_done'),
    url(r'^password/reset/$', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset.html',
        html_email_template_name='registration/password_reset_email.html',
        email_template_name='registration/password_reset_email.txt',
    ), name='password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
        ), name='password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html',
    ), name='password_reset_complete'),
    url(r'^password/reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html',
    ), name='password_reset_done'),
    url(r'^social/error/$', register.social_auth_error, name='social_auth_error'),

    url(r'^2fa/$', two_factor.TwoFactorLoginView.as_view(), name='login_2fa'),
    url(r'^2fa/enable/$', two_factor.TOTPEnableView.as_view(), name='enable_2fa'),
    url(r'^2fa/disable/$', two_factor.TOTPDisableView.as_view(), name='disable_2fa'),
    url(r'^2fa/webauthn/attest/$', two_factor.WebAuthnAttestationView.as_view(), name='webauthn_attest'),
    url(r'^2fa/webauthn/assert/$', two_factor.WebAuthnAttestView.as_view(), name='webauthn_assert'),
    url(r'^2fa/webauthn/delete/(?P<pk>\d+)$', two_factor.WebAuthnDeleteView.as_view(), name='webauthn_delete'),

    url(r'api/token/generate/$', user.generate_api_token, name='generate_api_token'),
    url(r'api/token/remove/$', user.remove_api_token, name='remove_api_token'),
]


def exception(request):
    if not request.user.is_superuser:
        raise Http404()
    raise RuntimeError('@Xyene asked me to cause this')


def paged_list_view(view, name):
    return include([
        url(r'^$', view.as_view(), name=name),
        url(r'^(?P<page>\d+)$', view.as_view(), name=name),
    ])


urlpatterns = [
    url(r'^$', blog.PostList.as_view(template_name='home.html', title=_('Home')), kwargs={'page': 1}, name='home'),
    url(r'^500/$', exception),
    url(r'^admin/', admin.site.urls),
    url(r'^about/', about.about, name='about'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include(register_patterns)),
    url(r'^', include('social_django.urls')),

    url(r'^problems/$', problem.ProblemList.as_view(), name='problem_list'),
    url(r'^problems/random/$', problem.RandomProblem.as_view(), name='problem_random'),

    url(r'^problem/(?P<problem>[^/]+)', include([
        url(r'^$', problem.ProblemDetail.as_view(), name='problem_detail'),
        url(r'^/editorial$', problem.ProblemSolution.as_view(), name='problem_editorial'),
        url(r'^/raw$', problem.ProblemRaw.as_view(), name='problem_raw'),
        url(r'^/pdf$', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        url(r'^/pdf/(?P<language>[a-z-]+)$', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        url(r'^/clone', problem.ProblemClone.as_view(), name='problem_clone'),
        url(r'^/submit$', problem.ProblemSubmit.as_view(), name='problem_submit'),
        url(r'^/resubmit/(?P<submission>\d+)$', problem.ProblemSubmit.as_view(), name='problem_submit'),

        url(r'^/rank/', paged_list_view(ranked_submission.RankedSubmissions, 'ranked_submissions')),
        url(r'^/submissions/', paged_list_view(submission.ProblemSubmissions, 'chronological_submissions')),
        url(r'^/submissions/(?P<user>\w+)/', paged_list_view(submission.UserProblemSubmissions, 'user_submissions')),

        url(r'^/$', lambda _, problem: HttpResponsePermanentRedirect(reverse('problem_detail', args=[problem]))),

        url(r'^/test_data$', ProblemDataView.as_view(), name='problem_data'),
        url(r'^/test_data/init$', problem_init_view, name='problem_data_init'),
        url(r'^/test_data/diff$', ProblemSubmissionDiff.as_view(), name='problem_submission_diff'),
        url(r'^/data/(?P<path>.+)$', problem_data_file, name='problem_data_file'),

        url(r'^/tickets$', ticket.ProblemTicketListView.as_view(), name='problem_ticket_list'),
        url(r'^/tickets/new$', ticket.NewProblemTicketView.as_view(), name='new_problem_ticket'),

        url(r'^/manage/submission', include([
            url('^$', problem_manage.ManageProblemSubmissionView.as_view(), name='problem_manage_submissions'),
            url('^/rejudge$', problem_manage.RejudgeSubmissionsView.as_view(), name='problem_submissions_rejudge'),
            url('^/rejudge/preview$', problem_manage.PreviewRejudgeSubmissionsView.as_view(),
                name='problem_submissions_rejudge_preview'),
            url('^/rejudge/success/(?P<task_id>[A-Za-z0-9-]*)$', problem_manage.rejudge_success,
                name='problem_submissions_rejudge_success'),
            url('^/rescore/all$', problem_manage.RescoreAllSubmissionsView.as_view(),
                name='problem_submissions_rescore_all'),
            url('^/rescore/success/(?P<task_id>[A-Za-z0-9-]*)$', problem_manage.rescore_success,
                name='problem_submissions_rescore_success'),
        ])),
    ])),

    url(r'^submissions/', paged_list_view(submission.AllSubmissions, 'all_submissions')),
    url(r'^submissions/user/(?P<user>\w+)/', paged_list_view(submission.AllUserSubmissions, 'all_user_submissions')),

    url(r'^src/(?P<submission>\d+)$', submission.SubmissionSource.as_view(), name='submission_source'),
    url(r'^src/(?P<submission>\d+)/raw$', submission.SubmissionSourceRaw.as_view(), name='submission_source_raw'),

    url(r'^submission/(?P<submission>\d+)', include([
        url(r'^$', submission.SubmissionStatus.as_view(), name='submission_status'),
        url(r'^/abort$', submission.abort_submission, name='submission_abort'),
    ])),

    url(r'^users/', include([
        url(r'^$', user.users, name='user_list'),
        url(r'^(?P<page>\d+)$', lambda request, page:
            HttpResponsePermanentRedirect('%s?page=%s' % (reverse('user_list'), page))),
        url(r'^find$', user.user_ranking_redirect, name='user_ranking_redirect'),
    ])),

    url(r'^user$', user.UserAboutPage.as_view(), name='user_page'),
    url(r'^edit/profile/$', user.edit_profile, name='user_edit_profile'),
    url(r'^user/(?P<user>\w+)', include([
        url(r'^$', user.UserAboutPage.as_view(), name='user_page'),
        url(r'^/solved', include([
            url(r'^$', user.UserProblemsPage.as_view(), name='user_problems'),
            url(r'/ajax$', user.UserPerformancePointsAjax.as_view(), name='user_pp_ajax'),
        ])),

judge/models/comment.py
import itertools

from django.contrib.contenttypes.fields import GenericRelation
from django.core.cache import cache
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import CASCADE
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from reversion.models import Version

from judge.models.contest import Contest
from judge.models.interface import BlogPost
from judge.models.problem import Problem
from judge.models.profile import Profile
from judge.utils.cachedict import CacheDict

__all__ = ['Comment', 'CommentLock', 'CommentVote']

comment_validator = RegexValidator(r'^[pcs]:[a-z0-9]+$|^b:\d+$',
                                   _(r'Page code must be ^[pcs]:[a-z0-9]+$|^b:\d+$'))


class VersionRelation(GenericRelation):
    def __init__(self):
        super(VersionRelation, self).__init__(Version, object_id_field='object_id')

    def get_extra_restriction(self, where_class, alias, remote_alias):
        cond = super(VersionRelation, self).get_extra_restriction(where_class, alias, remote_alias)
        field = self.remote_field.model._meta.get_field('db')
        lookup = field.get_lookup('exact')(field.get_col(remote_alias), 'default')
        cond.add(lookup, 'AND')
        return cond


class Comment(MPTTModel):
    author = models.ForeignKey(Profile, verbose_name=_('commenter'), on_delete=CASCADE)
    time = models.DateTimeField(verbose_name=_('posted time'), auto_now_add=True)
    page = models.CharField(max_length=30, verbose_name=_('associated page'), db_index=True,
                            validators=[comment_validator])
    score = models.IntegerField(verbose_name=_('votes'), default=0)
    body = models.TextField(verbose_name=_('body of comment'), max_length=8192)
    hidden = models.BooleanField(verbose_name=_('hide the comment'), default=0)
    parent = TreeForeignKey('self', verbose_name=_('parent'), null=True, blank=True, related_name='replies',
                            on_delete=CASCADE)
    versions = VersionRelation()

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

    class MPTTMeta:
        order_insertion_by = ['-time']

    @classmethod
    def most_recent(cls, user, n, batch=None):
        queryset = cls.objects.filter(hidden=False).select_related('author__user') \
            .defer('author__about', 'body').order_by('-id')

        problem_access = CacheDict(lambda code: Problem.objects.get(code=code).is_accessible_by(user))
        contest_access = CacheDict(lambda key: Contest.objects.get(key=key).is_accessible_by(user))
        blog_access = CacheDict(lambda id: BlogPost.objects.get(id=id).can_see(user))

        if user.is_superuser:
            return queryset[:n]
        if batch is None:
            batch = 2 * n
        output = []
        for i in itertools.count(0):
            slice = queryset[i * batch:i * batch + batch]
            if not slice:
                break
            for comment in slice:
                if comment.page.startswith('p:') or comment.page.startswith('s:'):
                    try:
                        if problem_access[comment.page[2:]]:
                            output.append(comment)
                    except Problem.DoesNotExist:
                        pass
                elif comment.page.startswith('c:'):
                    try:
                        if contest_access[comment.page[2:]]:
                            output.append(comment)
                    except Contest.DoesNotExist:
                        pass
                elif comment.page.startswith('b:'):
                    try:
                        if blog_access[comment.page[2:]]:
                            output.append(comment)
                    except BlogPost.DoesNotExist:
                        pass
                else:
                    output.append(comment)
                if len(output) >= n:
                    return output
        return output

    @cached_property
    def link(self):
        try:
            link = None
            if self.page.startswith('p:'):
                link = reverse('problem_detail', args=(self.page[2:],))
            elif self.page.startswith('c:'):
                link = reverse('contest_view', args=(self.page[2:],))
            elif self.page.startswith('b:'):
                key = 'blog_slug:%s' % self.page[2:]
                slug = cache.get(key)
                if slug is None:
                    try:
                        slug = BlogPost.objects.get(id=self.page[2:]).slug
                    except ObjectDoesNotExist:
                        slug = ''
                    cache.set(key, slug, 3600)
                link = reverse('blog_post', args=(self.page[2:], slug))
            elif self.page.startswith('s:'):
                link = reverse('problem_editorial', args=(self.page[2:],))
        except Exception:
            link = 'invalid'
        return link

    @classmethod
    def get_page_title(cls, page):
        try:
            if page.startswith('p:'):
                return Problem.objects.values_list('name', flat=True).get(code=page[2:])
            elif page.startswith('c:'):
                return Contest.objects.values_list('name', flat=True).get(key=page[2:])
            elif page.startswith('b:'):
                return BlogPost.objects.values_list('title', flat=True).get(id=page[2:])
            elif page.startswith('s:'):
                return _('Editorial for %s') % Problem.objects.values_list('name', flat=True).get(code=page[2:])
            return '<unknown>'
        except ObjectDoesNotExist:
            return '<deleted>'

    @cached_property
    def page_title(self):
        return self.get_page_title(self.page)

    def is_accessible_by(self, user):
        if self.page.startswith('p:') or self.page.startswith('s:'):
            return Problem.objects.get(code=self.page[2:]).is_accessible_by(user)
        elif self.page.startswith('c:'):
            return Contest.objects.get(key=self.page[2:]).is_accessible_by(user)
        elif self.page.startswith('b:'):
            return BlogPost.objects.get(id=self.page[2:]).can_see(user)
        else:
            return True

    def get_absolute_url(self):
        return '%s#comment-%d' % (self.link, self.id)

    def __str__(self):
        return '%(page)s by %(user)s' % {'page': self.page, 'user': self.author.user.username}

        # Only use this when queried with
        # .prefetch_related(Prefetch('votes', queryset=CommentVote.objects.filter(voter_id=profile_id)))
        # It's rather stupid to put a query specific property on the model, but the alternative requires
        # digging Django internals, and could not be guaranteed to work forever.
        # Hence it is left here for when the alternative breaks.
        # @property
        # def vote_score(self):
        #    queryset = self.votes.all()
        #    if not queryset:
        #        return 0
        #    return queryset[0].score


class CommentVote(models.Model):
    voter = models.ForeignKey(Profile, related_name='voted_comments', on_delete=CASCADE)
    comment = models.ForeignKey(Comment, related_name='votes', on_delete=CASCADE)
    score = models.IntegerField()

    class Meta:
        unique_together = ['voter', 'comment']
        verbose_name = _('comment vote')
        verbose_name_plural = _('comment votes')


class CommentLock(models.Model):
    page = models.CharField(max_length=30, verbose_name=_('associated page'), db_index=True,
                            validators=[comment_validator])

    class Meta:
        permissions = (
            ('override_comment_lock', _('Override comment lock')),
        )

    def __str__(self):
        return str(self.page)

templates/comments/content.html
{{ comment.body|markdown('comment', MATH_ENGINE)|reference|str|safe }}

templates/comments/edit-ajax.html
<div class="comment-submit">
    <form id="comment-edit" action="{{ request.get_full_path() }}" method="post">
        <span style="display: none" class="comment-id">{{ comment.id }}</span>
        <span style="display: none" class="read-back">{{ url('comment_content', comment.id) }}</span>
        {% csrf_token %}
        {% if form.non_field_errors() or form.body.errors %}
            <div class="form-errors">
                {{ form.non_field_errors() }}
                {{ form.body.errors }}
            </div>
        {% endif %}
        <div class="comment-post-wrapper">
            <div id="comment-form-body">{{ form.body }}</div>
        </div>
        <hr>
        <input style="float: right" type="submit" value="Post!" class="button">
    </form>
</div>

templates/comments/edit.html
{% extends "base.html" %}
{% block media %}
    {% compress css %}
        {{ form.media.css }}
    {% endcompress %}
{% endblock %}

{% block js_media %}
    {{ form.media.js }}
{% endblock %}
{% block body %}
    <div class="form-area">{% include "comments/edit-ajax.html" %}</div>
{% endblock %}

templates/comments/list.html
<div id="comments" class="comment-area">
    <h2><i style="padding-right: 0.3em" class="fa fa-comments"></i>{{ _('Comments') }}</h2>
    {% if has_comments %}
        <ul class="comments top-level-comments new-comments">
            {% set logged_in = request.user.is_authenticated %}
            {% set profile = request.profile if logged_in else None %}
            {% for node in mptt_tree(comment_list) recursive %}
                <li id="comment-{{ node.id }}" data-revision="{{ node.revisions - 1 }}"
                    data-max-revision="{{ node.revisions - 1 }}"
                    data-revision-ajax="{{ url('comment_revision_ajax', node.id) }}" class="comment">
                    <div class="comment-display{% if node.score <= vote_hide_threshold %} bad-comment{% endif %}">
                        <div class="info">
                            <div class="vote">
                                {% if logged_in %}
                                    <a href="javascript:comment_upvote({{ node.id }})"
                                       class="upvote-link fa fa-chevron-up fa-fw{% if node.vote_score == 1 %} voted{% endif %}"></a>
                                {% else %}
                                    <a href="javascript:alert('{{ _('Please login to vote')|escapejs }}')" title="{{ _('Please login to vote') }}"
                                       class="upvote-link fa fa-chevron-up fa-fw"></a>
                                {% endif %}
                                <br>
                                <div class="comment-score">{{ node.score }}</div>
                                {% if logged_in %}
                                    <a href="javascript:comment_downvote({{ node.id }})"
                                       class="downvote-link fa fa-chevron-down fa-fw{% if node.vote_score == -1 %} voted{% endif %}"></a>
                                {% else %}
                                    <a href="javascript:alert('{{ _('Please login to vote')|escapejs }}')" title="{{ _('Please login to vote') }}"
                                       class="downvote-link fa fa-chevron-down fa-fw"></a>
                                {% endif %}
                            </div>
                            {% with author=node.author, user=node.author.user %}
                                <a href="{{ url('user_page', user.username) }}" class="user">
                                    <img src="{{ gravatar(author, 135) }}" class="gravatar">
                                </a>
                            {% endwith %}
                        </div>
                        <div class="detail">
                            <div class="header">
                                {{ link_user(node.author) }}&nbsp;
                                {{ relative_time(node.time, abs=_('commented on {time}'), rel=_('commented {time}')) }}
                                <span class="comment-spacer"></span>
                                <span class="comment-operation">
                                {% if node.revisions > 1 %}
                                    <span class="comment-edits">
                                        <a href="javascript:show_revision({{ node.id }}, -1)"
                                           class="previous-revision">&larr;</a>
                                        <span class="comment-edit-text">
                                            {% if node.revisions > 2 %}
                                                {% trans edits=node.revisions - 1 %}edit {{ edits }}{% endtrans %}
                                            {% else %}
                                                {{ _('edited') }}
                                            {% endif %}
                                        </span>
                                        <a href="javascript:show_revision({{ node.id }}, 1)" style="visibility: hidden"
                                           class="next-revision">&rarr;</a>
                                    </span>
                                {% else %}
                                    <span class="comment-edits"></span>
                                {% endif %}
                                    <a href="#comment-{{ node.id }}" title="{{ _('Link') }}" class="comment-link">
                                    <i class="fa fa-link fa-fw"></i>
                                </a>
                                    {% if logged_in and not comment_lock %}
                                        {% set can_edit = node.author.id == profile.id and not profile.mute %}
                                        {% if can_edit %}
                                            <a data-featherlight="{{ url('comment_edit_ajax', node.id) }}"
                                               href="{{ url('comment_edit', node.id) }}"
                                               title="{{ _('Edit') }}" class="edit-link">
                                            <i class="fa fa-pencil fa-fw"></i>
                                        </a>
                                        {% else %}
                                            <a href="javascript:reply_comment({{ node.id }})"
                                               title="{{ _('Reply') }}">
                                            <i class="fa fa-reply fa-fw"></i>
                                        </a>
                                        {% endif %}
                                        {% if perms.judge.change_comment %}
                                            {% if can_edit %}
                                                <a href="javascript:reply_comment({{ node.id }})"
                                                   title="{{ _('Reply') }}"><i class="fa fa-reply fa-fw"></i></a>
                                            {% else %}
                                                <a data-featherlight="{{ url('comment_edit_ajax', node.id) }}"
                                                   href="{{ url('comment_edit', node.id) }}" title="{{ _('Edit') }}"
                                                   class="edit-link"><i class="fa fa-pencil fa-fw"></i></a>
                                            {% endif %}
                                            <a data-featherlight="{{ url('comment_votes_ajax', node.id) }}"
                                               title="{{ _('Votes') }}" class="votes-link"><i class="fa fa-bar-chart fa-fw"></i></a>
                                            <a href="javascript:" title="{{ _('Hide') }}" data-id="{{ node.id }}"
                                               class="hide-comment"><i class="fa fa-trash fa-fw"></i></a>
                                            <a href="{{ url('admin:judge_comment_change', node.id) }}"
                                               title="{{ _('Admin') }}"><i class="fa fa-cog fa-fw"></i></a>
                                        {% endif %}
                                    {% endif %}
                            </span>
                            </div>
                            <div class="content content-description">
                                <div class="comment-body"{% if node.score <= vote_hide_threshold %} style="display:none"{% endif %}>
                                    {{ node.body|markdown('comment', MATH_ENGINE, True)|reference|str|safe }}
                                </div>
                                {% if node.score <= vote_hide_threshold %}
                                    <div class="comment-body bad-comment-body">
                                        <p>
                                            {% trans id=node.id %}
                                                This comment is hidden due to too much negative feedback.
                                                Click <a href="javascript:comment_show_content({{ id }})">here</a> to view it.
                                            {% endtrans %}
                                        </p>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </li>
                <ul id="comment-{{ node.id }}-reply" class="reply-comment" hidden></ul>
                {% with children=node.get_children() %}
                    {% if children %}
                        <ul id="comment-{{ node.id }}-children" class="comments">{{ loop(children) }}</ul>
                    {% endif %}
                {% endwith %}
            {% endfor %}
        </ul>
    {% elif not comment_lock %}
        <p class="no-comments-message">{{ _('There are no comments at the moment.') }}</p>
    {% endif %}

    {% if request.user.is_authenticated and comment_form and not comment_lock %}
        <div id="new-comment" class="form-area comment-submit">
            {% block comment_submit_title %}
                <h3>{{ _('New comment') }}</h3>
                <hr>
            {% endblock %}
            {% if is_new_user %}
                <div style="margin-bottom: 0" class="alert alert-info">
                    {{ _('You need to have solved at least one problem before your voice can be heard.') }}
                </div>
            {% else %}
                <form class="comment-submit-form" action="" method="post">
                    {% csrf_token %}
                    {% if comment_form.errors %}
                        <div id="form-errors">
                            {{ comment_form.non_field_errors() }}
                            {{ comment_form.parent.errors }}
                            {% if comment_form.body.errors %}{{ _('Invalid comment body.') }}{% endif %}
                        </div>
                    {% endif %}
                    {{ comment_form.parent }}
                    <div class="comment-post-wrapper">
                        <div id="comment-form-body">{{ comment_form.body }}</div>
                    </div>
                    <hr>
                    <input style="float:right" type="submit" value="{{ _('Post!') }}" class="button">
                </form>
            {% endif %}
        </div>
    {% endif %}

    {% if comment_lock %}
        <div class="alert alert-warning comment-lock">
            {{ _('Comments are disabled on this page.') }}
        </div>
    {% endif %}
</div>

templates/comments/math.html
{% compress js, inline %}
    <script src="{{ static('pagedown_math.js') }}"></script>
{% endcompress %}

templates/comments/preview.html
{{ preview_data|markdown('comment', MATH_ENGINE)|reference|str|safe }}
{% if REQUIRE_JAX %}
    <div data-config="{{ static('mathjax_config.js') }}" class="require-mathjax-support"></div>
{% endif %}

templates/comments/revision-ajax.html
{% with node=revision.field_dict %}
    <div class="comment-body">{{ node.body|markdown('comment', MATH_ENGINE)|reference|str|safe }}</div>
{% endwith %}

templates/comments/votes.html
<h2 style="text-align: center">{{ _('Votes') }}</h2>
<table class="table" style="display: table">
    <thead>
    <tr>
        <th>{{ _('Voter') }}</th>
        <th>{{ _('Score') }}</th>
    </tr>
    </thead>
    <tbody>
    {% for vote in votes %}
        <tr>
            <td>{{ link_user(vote.voter) }}</td>
            <td>{{ vote.score }}</td>
        </tr>
    {% else %}
        <tr>
            <td colspan="2">{{ _('No votes') }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>